server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        - id: user-service-route
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/users/**

        - id: booking-service-route
          uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/bookings/**

        - id: review-service-route
          uri: ${REVIEW_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/reviews/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8082}
  booking-service:
    url: ${BOOKING_SERVICE_URL:http://localhost:8083}
  review-service:
    url: ${REVIEW_SERVICE_URL:http://localhost:8085}
